# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Original: https://github.com/forexample/hunter-simple/blob/master/.travis.yml

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For off screen rendering
      - libegl1-mesa-dev
      - libosmesa6-dev

      # glapi
      - libgl1-mesa-dev

      # xorg-macros: https://github.com/BlueDragonX/xf86-input-mtrack/issues/27#issuecomment-186871891
      - xutils-dev
      - xserver-xorg-dev-lts-trusty

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      - python3-pip

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      #- g++-5
      #- gcc-5

env:
  global:
    - secure: "lymcX03VKPnytwpHgNqWI6JfGZuEHYpIOY9eM8BvT6ODXHgdTyGQND1VZZ96PJFYhs+pgAJl7iSZTwlKny/lLmwcTNAWu4+lJas/mgUQFRKfXLa0l5KosqVry8FmWmnSMtC2jsKPRF/fv9XeCEn9dOAZT1yfpLTeRZ22bpq/1/1+TVGqajfNZIX4W4kY0q/i/RK17RTsYCWrTeNU1y5C6hP2SK4mVAll5I2cJvF5SuxdOc6D19htIj6zOLSVadocPhWRD4yRoLLIlmX6IRmMqfTvArMv4D3aOVcU+Ep44oLyjny68st6mRdRa5TXqsUp6Wy/YCf1gEmXJ1CqyKtXASBhlB3Q5zPlTx6guMmJIJ5MMr7CNtoF86TQ47zNQAezHUnvZ+hckliOfkeoxnRHqBGvKLGN9IrKl3fNSRHFpvkXgSy0apnCyJKUaeABNhwoVlVuZw8D5Gyyhg+2OAX36KtHNeB6AvcSbZCJMGVqqidXi5p6slpz24Grdzh88pGtd4YXZzPuuy4uRWShl5wxsUKhmKz6uz3Q8ZYYlH7pa0xf9wRnInXYQKBqSzn8VkQIp5EFVIReh6nr4HsfisGUwoJFLZn6zjDvFzZVJHVzXfRj+Qx3nAMSNBXIAJieZL93yhNr/Erzftn0/M43SlYeO+GQFO54+28giNIF4UyNjTA="

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc INSTALL=--strip MESA=ON TEST=--test

    # }

    # OSX {

    # Try to match toolchains from ingenue deep tests to improve cache hits:
    # https://github.com/ingenue/hunter/blob/pkg.opencv/.travis.yml

    - os: osx
      osx_image: xcode8.3      
      env: CONFIG=Release TOOLCHAIN=ios-nocodesign-10-3-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install MESA=OFF

    - os: osx
      osx_image: xcode8.3      
      env: CONFIG=Release TOOLCHAIN=osx-10-12 INSTALL=--install MESA=OFF

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon INSTALL=--strip MESA=OFF TEST=--test

    # }

before_install:

  # Add '--quiet' to avoid leaking the token to logs
  - git submodule update --init --recursive --quiet

install:
  # Info about OS
  - uname -a

  # Disable autoupdate
  # * https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
  - export HOMEBREW_NO_AUTO_UPDATE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:

  - >
    travis_wait 200 polly.py
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --ios-multiarch --ios-combined
    --fwd HUNTER_CONFIGURATION_TYPES=${CONFIG}
    OGLES_GPGPU_BUILD_TESTS=ON
    OGLES_GPGPU_USE_OSMESA=${MESA}
    GAUZE_ANDROID_USE_EMULATOR=YES
    HUNTER_CONFIGURATION_TYPES=${CONFIG}
    HUNTER_SUPPRESS_LIST_OF_FILES=ON
    --jobs 2
    ${INSTALL} ${TEST}

branches:
  except:
    - /^pr\..*/
